version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test_regression_model_py36:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/project/packages/regression_model
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run tests with Python 3.6
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py36

  train_and_upload_regression_model:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/project/packages/regression_model
    steps:
      - checkout:
          path: ~/project
      - persist_to_workspace:
          root: ~/project
          path: .
      - run:
          name: Setup venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r ~/project/packages/regression_model/requirements.txt
      - run:
          name: Train model
          command: |
            . venv/bin/activate
            python3 ~/project/packages/regression_model/regression_model/train_pipeline.py
      - run: 
          name: Publish model to Gemfury
          command: |
            . venv/bin/activate
            chmod +x ~/project/scripts/publish_model.sh
            ~/project/scripts/publish_model.sh ~/project/packages/regression_model/

workflows:
  version: 2.1
  test-all:
    jobs:
      - train_and_upload_regression_model
      - test_regression_model_py36
      - train_and_upload_regression_model:
          requires:
            - test_regression_model_py36



